# Generated by Django 3.1.4 on 2020-12-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
