# Generated by Django 3.1.4 on 2020-12-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201228_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
