# Generated by Django 3.1.4 on 2021-02-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('name', models.CharField(help_text='测试报告', max_length=200, unique=True, verbose_name='测试报告')),
                ('result', models.BooleanField(default=1, help_text='执行结果', verbose_name='执行结果')),
                ('count', models.IntegerField(help_text='用例总数', verbose_name='用例总数')),
                ('success', models.IntegerField(help_text='成功总数', verbose_name='成功总数')),
                ('html', models.TextField(blank=True, help_text='报告源码', null=True, verbose_name='报告源码')),
                ('summary', models.TextField(blank=True, default='', help_text='报告详情', null=True, verbose_name='报告详情')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'db_reports',
            },
        ),
    ]
