# Generated by Django 3.1.4 on 2021-02-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debugtalks',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('name', models.CharField(default='debugtalks.py', help_text='debugtalks名称', max_length=200, verbose_name='debugtalks名称')),
                ('debugtalk', models.TextField(default='#debugtalks', help_text='debug文件', null=True)),
                ('project', models.OneToOneField(help_text='所属项目 ', on_delete=django.db.models.deletion.CASCADE, related_name='debugtalks', to='projects.projects')),
            ],
            options={
                'verbose_name': 'debug.py文件',
                'verbose_name_plural': 'debug.py文件',
                'db_table': 'db_debugtalks',
            },
        ),
    ]
